# Generated by Django 4.2.3 on 2023-07-25 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('faixa_salarial', models.CharField(choices=[('A', 'Até 1.000'), ('B', 'De 1.000 a 2.000'), ('C', 'De 2.000 a 3.000'), ('D', 'Acima de 3.000')], max_length=1)),
                ('requisitos', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TG', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PS', 'Pós / MBA / Mestrado'), ('DR', 'Doutorado')], max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensao_salarial', models.CharField(choices=[('A', 'Até 1.000'), ('B', 'De 1.000 a 2.000'), ('C', 'De 2.000 a 3.000'), ('D', 'Acima de 3.000')], max_length=1)),
                ('experiencia', models.TextField()),
                ('ultima_escolaridade', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TG', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PS', 'Pós / MBA / Mestrado'), ('DR', 'Doutorado')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='jobs.vaga')),
            ],
        ),
    ]
