# Generated by Django 4.1.9 on 2023-07-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary_range', models.CharField(choices=[('1000', 'Até 1.000'), ('1000-2000', 'De 1.000 a 2.000'), ('2000-3000', 'De 2.000 a 3.000'), ('3000+', 'Acima de 3.000')], max_length=50)),
                ('education_required', models.CharField(choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Ensino Superior'), ('pos_mba_mestrado', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_expectation', models.CharField(choices=[('1000', 'Até 1.000'), ('1000-2000', 'De 1.000 a 2.000'), ('2000-3000', 'De 2.000 a 3.000'), ('3000+', 'Acima de 3.000')], max_length=50)),
                ('experience', models.CharField(choices=[('no_experience', 'Sem experiência'), ('1-3_years', '1 a 3 anos'), ('3-5_years', '3 a 5 anos'), ('5+_years', 'Mais de 5 anos')], max_length=50)),
                ('last_education', models.CharField(choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Ensino Superior'), ('pos_mba_mestrado', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_applications', models.ManyToManyField(related_name='candidates', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
